// client/src/app/home/home.component.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import ResponseUserData from './home.model';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HomeComponent implements OnInit {
  userData: ResponseUserData;

  constructor(private route: ActivatedRoute, private cd: ChangeDetectorRef) {}

  ngOnInit(): void {
    this.userData = this.route.snapshot.data as ResponseUserData;
    this.cd.detectChanges();
  }
}

<div class="containter" *ngIf="userData && userData.user">
  <img src="{{ userData.user.avatar }}" alt="discord avatar" class="containter__image" />
  <h1 class="containter__header">Welcome {{ userData.user.username }}</h1>
  <div class="card">
    <h2 class="card__header">Your data</h2>
    <ul class="card__list">
      <li class="card__list-item">
        <strong class="card__list-label">discord_id:</strong>
        <span class="card__list-txt">{{ userData.user.discord_id }}</span>
      </li>

      <li class="card__list-item">
        <strong class="card__list-label">username:</strong>
        <span class="card__list-txt">{{ userData.user.username }}</span>
      </li>

      <li class="card__list-item">
        <strong class="card__list-label">permissions:</strong>
        <span class="card__list-txt"> {{ userData.user.permissions_str }} </span>
      </li>

      <li class="card__list-item">
        <strong class="card__list-label">avatar:</strong>
        <span class="card__list-txt">{{ userData.user.avatar }}</span>
      </li>

      <li class="card__list-item">
        <strong class="card__list-label">exp:</strong>
        <span class="card__list-txt">{{ userData.user.exp }}</span>
      </li>
    </ul>
  </div>
</div>

// client/src/views/Home/Home.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import React from "react";
import { useParams } from "react-router-dom";
import "./Home.scss";
import MaterialIcon from "@material/react-material-icon";
import { useFetch } from "react-async";
import enviromant from "../../enviroment";
import UserData from "./Home.model";

export default function Home() {
  const { token }: { token: string } = useParams();
  const { data, error } = useFetch<UserData>(`${enviromant.API_URL}/auth`, {
    headers: { Authorization: `Bearer ${token}`, accept: "application/json" },
  });

  if (error) throw error;

  localStorage.setItem("user_token", data?.token ?? "");
  localStorage.setItem("user_img", data?.user?.avatar ?? "");

  return (
    <>
      <div className="container">
        <h1 className="container__header">Welcome {data?.user?.username}</h1>
        <hr />
        <div className="card">
          <h2 className="card__header">Your data</h2>
          <ul className="card__list">
            <li className="card__list-item">
              <MaterialIcon icon="fingerprint" title="discord_id" />
              <strong className="card__list-label">discord_id:</strong>
              <span className="card__list-txt">{data?.user?.discord_id}</span>
            </li>

            <li className="card__list-item">
              <MaterialIcon icon="account_box" title="discord_id" />
              <strong className="card__list-label">username:</strong>
              <span className="card__list-txt">{data?.user?.username}</span>
            </li>

            <li className="card__list-item">
              <MaterialIcon icon="perm_identity" title="discord_id" />
              <strong className="card__list-label">permissions:</strong>
              <span className="card__list-txt">
                {data?.user?.permissions_str ?? ""}
              </span>
            </li>

            <li className="card__list-item">
              <MaterialIcon icon="image" title="discord_id" />
              <strong className="card__list-label">avatar:</strong>
              <span className="card__list-txt">{data?.user?.avatar}</span>
            </li>

            <li className="card__list-item">
              <MaterialIcon icon="schedule" title="discord_id" />
              <strong className="card__list-label">exp:</strong>
              <span className="card__list-txt">{data?.user?.exp}</span>
            </li>
          </ul>
        </div>
      </div>
    </>
  );
}
